# **`Experiment 4 : Jocobi's method for eigenvalues and eigenvectors`**

## **`aim`**

This laboratory session has several one main objective. You will
* compute the eigenvalues and eigenvectors of a matrix using jacobi's method


## **`Import numpy module using alias np`**

* Import **numpy** module as **np** .  **[4 marks]**

In [4]:
import numpy as np

* Import the functions **`eig`** and **`eigvals`** from **numpy.linalg** sub-module. **[5 marks]**

In [5]:
from numpy.linalg import eig, eigvals

* Create  symmetric matrix $\mathbf{A}$ using numpy **`array()`** function  **[6 marks]**

$$ \mathbf{A} = \begin{bmatrix} 
4 & -2 & 1 & -1 \\ -2 & 4 & -2 & 1 \\ 1 & -2 & 4 & -2 \\ -1 & 1 & -2 & 4\\ \end{bmatrix}   $$

In [6]:
A = np.array([[4, -2, 1, -1], [-2, 4, -2, 1], [1, -2, 4, -2], [-1, 1, -2, 4]])

* Print matrix **A** . **[2 marks]**

In [7]:
print(A)

[[ 4 -2  1 -1]
 [-2  4 -2  1]
 [ 1 -2  4 -2]
 [-1  1 -2  4]]


## **`definition of Jacobi's method`**

- study the following implementation of **`jacobi's method`** for solving eigenvalues and eigenvectors for symmetric matrix generated by the Artifical Intelligence tool **`deepseek`**.

In [18]:
def jacobi_eigenvalue(A, tol = 1e-10, max_iter = 1000):

    # get shape of matrix A
    n = A.shape[0] 

    # initialize eigenvector matrix V as identity matrix
    V = np.eye(n) 

    # initialize  work copy of A as D
    D = A.copy() 

    for _ in range(max_iter):
        # Find the largest off-diagonal element in current matrix D
        max_val = 0
        p , q = 0, 0
        for i in range(n) :
            for j in range(i+1, n):
                if abs(D[i,j]) > max_val :
                    max_val = abs(D[i,j])
                    p , q = i , j
                    
        # check for convergence
        if max_val < tol :
            break

        # compute rotation angle : theta
        if D[p , p ] == D[q , q] :
            theta = np.pi / 4
        else :
            theta = 0.5 * np.arctan(2 * D[p, q] / (D[p , p] - D[q , q]))

        # compute entries  for rotation matrix
        c = np.cos(theta)
        s = np.sin(theta)
        
        # initialize rotational matrix to identity matrix : S
        S = np.eye(n)
        S[p, p] = c
        S[p, q] = -s
        S[q, p] = s
        S[q, q] = c

        # Apply the rotation to D and V
        D = S.T @ D @ S
        V = V @ S

    # Extract eigenvalues
    eigenvalues = np.diag(D)

    # sort eigenvalues and corresponding eigenvectors
    idx = eigenvalues.argsort()[::-1]
    eigenvalues = eigenvalues[idx]
    eigenvectors = V[:, idx]

    return eigenvalues, eigenvectors

* Compute the eigenvalues and eigenvectors of matrix **A** using numpy **`jacobi_eigenvalue`** function. Store the return values in variables **eigenvalues** and **eigenvectors**. **[5 marks]**

In [12]:
eigenvalues, eigenvectors = jacobi_eigenvalue(A)

* Print out **eigenvalues**. **[2 marks]**

In [13]:
print(eigenvalues)

[8.54138127 3.61803399 2.45861873 1.38196601]


* Print out **eigenvectors**. **[2 marks]**

In [14]:
print(eigenvectors)

[[-0.45705607  0.60150096  0.5395366   0.37174803]
 [ 0.5395366  -0.37174803  0.45705607  0.60150096]
 [-0.5395366  -0.37174803 -0.45705607  0.60150096]
 [ 0.45705607  0.60150096 -0.5395366   0.37174803]]


* Compute the eigenvalues and eigenvectors of matrix **A** using numpy **`eig`** function. Store the return values in variables **eigenvalues** and **eigenvectors**. **[5 marks]**

In [15]:
eigenvalues, eigenvectors = eig(A)

* Print out **eigenvalues**. **[2 marks]**

In [16]:
print(eigenvalues)

[8.54138127 3.61803399 1.38196601 2.45861873]


* Print out **eigenvectors**. **[2 marks]**

In [17]:
print(eigenvectors)

[[ 0.45705607 -0.60150096  0.37174803 -0.5395366 ]
 [-0.5395366   0.37174803  0.60150096 -0.45705607]
 [ 0.5395366   0.37174803  0.60150096  0.45705607]
 [-0.45705607 -0.60150096  0.37174803  0.5395366 ]]
