# **`Experiment 3 : Matrix Operations`**

## **`aim`**

This laboratory session has several objectives. You will
* create a square matrix
* create a transpose matrix
* compute the determinant of square matrix
* compute the inverse of a square matrix
* compute the eigenvalues and eigenvectors of a matrix


## **`Import numpy module using alias np`**

* Import **numpy** module as **np** .  **[4 marks]**

In [1]:
import numpy as np

## **`Exercise 1. Create a square matrix `**

* Create  symmetric matrix $\mathbf{A}$ using numpy **`array()`** function  **[6 marks]**

$$ \mathbf{A} = \begin{bmatrix} 
4 & -2 & 1 & -1 \\ -2 & 4 & -2 & 1 \\ 1 & -2 & 4 & -2 \\ -1 & 1 & -2 & 4\\ \end{bmatrix}   $$

In [2]:
A = np.array([[4, -2, 1, -1], [-2, 4, -2, 1], [1, -2, 4, -2], [-1, 1, -2, 4]])

* Print matrix **A** . **[2 marks]**

In [3]:
print(A)

[[ 4 -2  1 -1]
 [-2  4 -2  1]
 [ 1 -2  4 -2]
 [-1  1 -2  4]]


## **`Exercise 2. Create a transpose matrix `**

* Compute the transpose of matrix **A** using the numpy **transpose** function. Store the return value in variable **B**. **[3 marks]**

In [4]:
B = np.fastCopyAndTranspose(A)

/tmp/ipykernel_63209/2177858357.py:1: DeprecationWarning: fastCopyAndTranspose and the underlying C function PyArray_CopyAndTranspose have been deprecated.

Use the transpose method followed by a C-order copy instead, e.g. ``arr.T.copy()``
  B = np.fastCopyAndTranspose(A)


* Print out  transpose matrix **B**. **[2 marks]**

In [5]:
print(B)

[[ 4 -2  1 -1]
 [-2  4 -2  1]
 [ 1 -2  4 -2]
 [-1  1 -2  4]]


* Show that matrix **A** is **`symmetric`**. **[4 marks]**

In [6]:
# symetric matrix
print(np.allclose(A, B))

True


## **`Exercise 3. Compute determinant of square matrix `**

* Import the determinant  function **`det`** from **numpy.linalg** sub-module. **[4 marks]**

In [ ]:
from numpy.linalg import det

* Compute the determinant of matrix **A** and store return value in **determinant**. **[3 marks]**

In [8]:
determinant = det(A)

* Print out the variable **determinant**. **[2 marks]**

In [9]:
print(determinant)

104.99999999999997


## **`Exercise 4. Compute inverse of square matrix `**

* Import the inverse  function **`inv`** from **numpy.linalg** sub-module. **[4 marks]**

In [10]:
from numpy.linalg import inv

* Compute the inverse of matrix **A** and store return value in **inverse**. **[3 marks]**

In [11]:
inverse = inv(A)

* Print out variable **inverse**. **[2 marks]**

In [12]:
print(inverse)

[[0.34285714 0.17142857 0.02857143 0.05714286]
 [0.17142857 0.41904762 0.18095238 0.02857143]
 [0.02857143 0.18095238 0.41904762 0.17142857]
 [0.05714286 0.02857143 0.17142857 0.34285714]]


* Compute the product of matrix **A** and its inverse using the numpy **`dot`** function. Store the return value in variable **`I`**. **[4 marks]**

In [13]:
I = np.dot(A, inverse)

* Print out varible **I**. **[2 marks]**

In [14]:
print(I)

[[ 1.00000000e+00  6.59194921e-17  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -8.32667268e-17  0.00000000e+00]
 [ 0.00000000e+00  2.08166817e-17  1.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17  1.38777878e-17  0.00000000e+00  1.00000000e+00]]


## **`Exercise 5. Compute eigenvalues of square matrix `**

* Import the functions **`eig`** and **`eigvals`** from **numpy.linalg** sub-module. **[5 marks]**

In [16]:
from numpy.linalg import eig, eigvals


* Compute the eigenvalues of matrix **A** using numpy **`eigvals`**. Store the return value in variable **eigenvalues**. **[3 marks]**

In [17]:
eigenvalues = eigvals(A)

* Print out **eigenvalues**. **[2 marks]**

In [18]:
print(eigenvalues)

[8.54138127 3.61803399 1.38196601 2.45861873]


* Compute the eigenvalues and eigenvectors of matrix **A** using numpy **`eig`** function. Store the return values in variables **eigenvalues** and **eigenvectors**. **[5 marks]**

In [22]:
eigenvalues, eignvenctors = eig(A)

* Print out **eigenvalues**. **[2 marks]**

In [23]:
print(eigenvalues)

[8.54138127 3.61803399 1.38196601 2.45861873]


* Print out **eigenvectors**. **[2 marks]**

In [24]:
print(eignvenctors)

[[ 0.45705607 -0.60150096  0.37174803 -0.5395366 ]
 [-0.5395366   0.37174803  0.60150096 -0.45705607]
 [ 0.5395366   0.37174803  0.60150096  0.45705607]
 [-0.45705607 -0.60150096  0.37174803  0.5395366 ]]
