# **`PHY 4031 Experiment 1 : Random numbers from numpy random module`**

## **`AIM`**

The Python **`Numpy`** library comes with a **`random`** module that contains functions for generating random numbers. This **`numpy.random`** module some simple random data generation methods, some permutation and distribution functions, and random generator functions. In this experiment, we are going to consider the Python **`numpy.random`** module  to

- **`produce lists of real random numbers between 0 and 1;`**
- **`produce a lists of integer random numbers within a given range;`**
- **`produce a lists of real random numbers within a range;`**
- **`produce a different random number sequence for each invocation`**

## **`Python numpy.random module`**

* Import **`numpy.random`** module

In [1]:
import numpy

* Save the contents of **`numpy.random`** module into the list **`contents`**

In [13]:
contents = numpy.random

* Print the list **`contents`**.

In [ ]:
print(contents)

<module 'numpy.random' from '/home/henryviyuyi/Desktop/4TH_YEAR_COMPUTATIONAL_PHYSICS_PROJECTS/.venv/lib/python3.8/site-packages/numpy/random/__init__.py'>


## **`Exercise 1 : Generate a single real random number`**

The random **`numpy.random.random()`** function generates a single random number in **`[0.0, 1.0)`**.

#### **`Instructions`**

* Import **`random()`** function from **`numpy.random`** module

In [5]:
from numpy.random import random

* Display help on numpy random **`random()`** function

In [6]:
help(random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



* Generate a single real random number in interval **`[0,1)`** and store it in variable **`ans`**.

In [8]:
ans = random()

* Print variable **`ans`**

In [9]:
print(ans)

0.06121528913977414


* Generate another single random number in range **`[0,1)`** and store it in variable **`ans`**.

In [10]:
ans = random()

* Print variable **`ans`**

In [11]:
print(ans)

0.32465025416678217


## **`Exercise 2 : Generate a single real random integer`**

The random **`numpy.random.randint()`** function generates a single random integer within a given interval **`[a, b)`**.

#### **`Instructions`**

* Import **`randint()`** function from **`numpy.random`** module

In [14]:
from numpy.random import randint

* Generate another single random integer in range **`[0,50)`** and store it in variable **`ans`**.

In [23]:
ans = randint(0,49)

* Print variable **`ans`**

In [20]:
print(ans)

20


* Generate  single random integer in range **`[30,100)`** and store it in variable **`ans`**.

In [24]:
ans = randint(30,99)

* Print variable **`ans`**

In [25]:
print(ans)

59


## **`Exercise 3 : Generate a list of real random numbers`**

The **`numpy.random.rand()`** function generates an array of random numbers or a matrix of random numbers in the **`0`** to  **`1`** (**`excluding 0 and 1`**).

#### **`Instructions`**

* Import **`rand()`** function from **`numpy.random`** module

In [26]:
from numpy.random import rand

* Display help on random **`rand`** function

In [27]:
help(rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

* Generate a numpy array of 10 random real number in the interval **`[0,1)`** and store it in variable **`ans`**.

In [28]:
ans = rand(10)

* Print variable **`ans`**

In [29]:
print(ans)

[0.53862366 0.7053332  0.62231951 0.42429302 0.07366796 0.73922401
 0.73826002 0.86036391 0.95286076 0.12164057]


* Generate a numpy $5 \times 5$ matrix random real number in the interval **`[0,1)`** and store it in variable **`ans`**.

In [30]:
ans = rand(5,5)

* Print variable **`ans`**

In [31]:
print(ans)

[[0.38264562 0.40822689 0.15913785 0.99591308 0.21369078]
 [0.05643202 0.0491676  0.59878046 0.46557423 0.91308697]
 [0.93432781 0.36486014 0.38376161 0.13789417 0.92776875]
 [0.19978285 0.79817182 0.66168329 0.17212575 0.24697391]
 [0.54403137 0.65646735 0.39245947 0.91950752 0.39634238]]


* Generate a numpy array of 10 random real number in the interval **`[0,50)`** and store it in variable **`ans`**.

In [35]:
ans = randint(0, 50, 10)

* Print variable **`ans`**

In [36]:
print(ans)

[12  1 32 45 32 42 48 17 26  3]


## **`Exercise 4 : Shuffling a list of random numbers`**

The **`numpy.random.shuffle()`** function takes one argument - a list. It then shuffles the elements of the list in place.

#### **`Instructions`**

* Import **`shuffle()`** function from **`numpy.random`** module

In [37]:
from numpy.random import shuffle

* Display help on **`shuffle()`** function

In [38]:
help(shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    .. note::
        New code should use the `~numpy.random.Generator.shuffle`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.
    
    Returns
    -------
    None
    
    See Also
    --------
    random.Generator.shuffle: which should be used for new code.
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random
    
    Multi-dimensional arrays are only s

* Generate a numpy array of **`10`** real random numbers and store it in variable **`numbers`**

In [41]:
numbers = rand(10)

* Print out numpy array **`numbers`**.

In [42]:
print(numbers)

[0.25115056 0.71626535 0.80468775 0.44082183 0.49548985 0.62682486
 0.36555085 0.59086809 0.33134108 0.93104211]


* Shuffle the numpy array **`numbers`** using the numpy random **`shuffle()`** function.

In [43]:
shuffle(numbers)

* Print the shuffled numpy array **`numbers`**

In [44]:
print(numbers)

[0.44082183 0.93104211 0.62682486 0.25115056 0.33134108 0.80468775
 0.59086809 0.71626535 0.49548985 0.36555085]


* Shuffle the numpy array **`numbers`** again using the numpy random **`shuffle()`** function.

In [45]:
shuffle(numbers)

* Print the shuffled numpy array **`numbers`**

In [46]:
print(numbers)

[0.93104211 0.71626535 0.80468775 0.25115056 0.49548985 0.62682486
 0.44082183 0.59086809 0.33134108 0.36555085]
